version: '3.4'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4       
    environment:
    - discovery.type=single-node
    - transport.host=127.0.0.1
    - ELASTIC_PASSWORD="secret"
    ports:
    - "9200:9200"
    - "9300:9300"

  kibana:    
    image: docker.elastic.co/kibana/kibana:6.1.4
    ports:
    - "5601:5601"
    depends_on:
    - elastic    
    links:
    - elastic:elastic-url
    environment:
    - ELASTICSEARCH_URL=http://elastic-url:9200
    - ELASTICSEARCH_PASSWORD="secret"
    
    
